- hosts: backup
  vars:
    date: "{{ lookup('pipe', 'date -u +%Y%m%d-%H%M%S') }}"
  user: root
  roles:
    - backup-parity
  tags: backup

- hosts: hf-spec-change
  vars:
    date: "{{ lookup('pipe', 'date -u +%Y%m%d-%H%M%S') }}"
    home: "/home/{{ poa_role }}"
  user: root
  become: true
  become_user: root
  roles:
    - hf-spec-change
  tags: hf-spec

- hosts: upd-scripts-validator
  vars:
    poa_role: validator
    username: validator
    date: "{{ lookup('pipe', 'date -u +%Y%m%d-%H%M%S') }}"
    home: "/home/{{ poa_role }}"
  user: root
  become: true
  become_user: root
  roles:
    - upd-scripts-validator
  tags: upd-validator
