- hosts: backup
  vars:
    date: "{{ lookup('pipe', 'date -u +%Y%m%d-%H%M%S') }}"
  user: root
  roles:
    - backup-parity
  tags: backup

- hosts: hf-spec-change
  vars:
    date: "{{ lookup('pipe', 'date -u +%Y%m%d-%H%M%S') }}"
    home: "/home/{{ poa_role }}"
  user: root
  roles:
    - hf-spec-change
  tags: hf-spec
