---
- name: Shutdown poa-netstats service
  service: name=poa-netstats state=stopped

- name: Shutdown poa-parity service
  service: name=poa-parity state=stopped

- name: Create backup directory
  file: path=/data state=directory

- name: Create blockchain archive
  archive:
    format: gz
    path: /home/{{ poa_role }}/parity_data
    dest: "/data/parity_data.tar.gz"

- name: Upload to s3
  s3:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    bucket: "{{ s3_bucket }}"
    object: "/parity_data-{{ date }}.tar.gz"
    src: "/data/parity_data.tar.gz"
    mode: put
  ignore_errors: yes

- name: Clean local backup storage
  file:
    state: absent
    path: "/data/"

- name: Launch poa-parity service
  service: name=poa-parity state=started

- name: Launch poa-netstats service
  service: name=poa-netstats state=started

